name: Check if the program works

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt install python3-tk
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Test script
      run: |
        source venv/bin/activate
        python main.py
